### ISSUE TITLE
Is it safe for LiFePo4?

### ISSUE THREAD

**Issue by ghamauricio** [megasaturnv/HX-2S-JH20-reverse-engineered_aka-2S-10A-Balance-Li-ion-Protection-PCB#3]
Hello. Thanks for the effort you put into it, but I'm no electronic guy.

Is it safe enough for LiFePo4 batteries? (They say it's a pretty safe chemistry)
If not, what would you recommend?

Also, are there any resistors I could change in order to keep the batteries between 10 and 90% charged?

Best regards!

**Comment by megasaturnv** [comment]
Sorry for the delay - I should probably follow up on this project and actually finish it. I'm not sure if it can balance LiFe cells, but my suggestion is to put 7.3v (3.65V * 2) across P+ and P- and then put two regular (discharged) Li-ion cells across B+, BM and B-. Measure the voltage across the Li-ion cells and check it doesn't exceed 3.65v. (You could also try one discharged Li-ion cell and another Li-ion cell at 3.65V)

As for the resistors, I don't think it has this feature. I would like to figure out if it can limit the charge to 90% as I rarely need to charge my Li-ion cells to 4.2V and I would prefer to charge them to just 4.0 or 4.1V. One solution I've used in the past is to put two diodes in parallel (facing opposite directions) and then put that in series with the cell. This way, the cell will never fully charge and it can even limit the discharge too. There are heat losses though, especially for high loads. You can use different types of diode to vary the voltage drop.

**Comment by Lanchon** [comment]
> Is it safe enough for LiFePo4 batteries?

absolutely not! it will overcharge them and risk fire or very fast degradation in the best case.

> One solution I've used in the past is to put two diodes in parallel (facing opposite directions) and then put that in series with the cell.

this is dangerous! it will effectively kill balancing, as to turn on the balancer you would need 4.2V + Vdrop of diode. which charge and discharge cycles, as the cells grow out of balance, one will inevitably overcharge.
